# Generated by Django 5.0.3 on 2024-06-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=50)),
                ('completed', models.BooleanField(default=False)),
                ('updated', models.DateField(auto_now_add=True)),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
